<?php

namespace backend\filters;
use yii\base\ActionFilter;
use yii\web\HttpException;

class AccessFilter extends ActionFilter
{
    /**
     * 操作执行之前要执行的代码
     */
    public function beforeAction($action)
    {
        //判断当前用户是否拥有当前操作权限
        //当前操作(路由)
        $permission=$action->uniqueId;
        if(!\Yii::$app->user->can($permission)){
            //判断是否登录
            if(\Yii::$app->user->isGuest){
                //通过操作获取控制器
                return $action->controller->redirect(\Yii::$app->user->loginUrl);
            }
            //抛出一个403的状态码
            throw new HttpException(403,'对不起，你没有该操作权限');
           //禁止执行
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}